### PR TITLE
Make the project work with current APIs

### PR DESCRIPTION
**Pull request by oyvindkinsey**
* Update the use of Avi-on's API to the current v3
* Fix incorrect use of avid (this now also supports groups etc)
* Add new function for constructing packets that work for both devices and groups
* Remove use of deprecated BLEDevices.rssi
* Replaced product_ids filtering with a type filter

### CODE REVIEW

**Comment by nayaverdier** [comment]
This looks great, thank you! I no longer have these lights but assuming you have tested this against your devices? If so I will merge and release a new version to pypi.

Don't worry about the linting, I'll try to fix the workflows before merging.

**Comment by oyvindkinsey** [comment]
I have tested the create_packet method for both devices and groups separately, and ran the following to go through the re-integration back into the halohome project

```
from halohome import halohome
import asyncio

async def main():
    halohome
    devices = await halohome.list_devices("xx@yy.zz", "****")
    connection = halohome.Connection(devices)
    for device in connection.devices:
        device_id = device.device_id
        if device_id == 33069: # the test device I'm targeting
            print(f"found device {device_id}")
            await device.set_brightness(50)
            await device.set_color_temp(2700)

asyncio.run(main())
```

Didn't you have a home assistant add-on using this at some point, or am I misremembering?

**Comment by nayaverdier** [comment]
Great, will merge this in today.

Yes, the home assistant integration never got merged. Apparently its bluetooth stack went through a lot of changes, completely breaking this library's usage of bleak. https://github.com/home-assistant/core/pull/58316

**Comment by oyvindkinsey** [comment]
I'm going to also extend this with support for groups, and once I get the basics integrated with Home Assistant again, I'll also look at adding polling/subscriptions in order to reflect the state of the devices when acted on externally. After that, discovery of new devices, adding them to the mesh, and removing them will come next.

Wrt HA, I remember that PR now. I'll try first spinning this up as a separate VM integrating with MQTT, and then when I have time to port this to C++, I'll make it work as an ESPHome type of device. 

I'm an utter n00b when it comes to python, so hoping that if I can cover extending this library with the core functionality, then maybe someone from the HA community will be able to help with the rest.

**Comment by nayaverdier** [comment]
@oyvindkinsey Released to pypi 0.6.0, thanks for the changes!

**Pull request merged**
